DROP TABLE K_MAP;
DROP TABLE K_MONSTER;
DROP TABLE K_MONSTER_CHARACTER;
DROP TABLE K_PATH;
DROP TABLE K_TOWER_CHARACTER;


CREATE TABLE K_MAP (
K_PK INTEGER PRIMARY KEY,
K_LEVEL INTEGER,
K_WIDTH INTEGER,
K_HEIGHT INTEGER,
K_WAVE_NUM INTEGER
);


CREATE TABLE K_PATH (
K_PK INTEGER PRIMARY KEY,
K_MAP_LEVEL INTEGER,
K_COLUMN INTEGER,
K_ROW INTEGER,
K_NEXT_PATH INTEGER
);

CREATE TABLE K_MONSTER_CHARACTER (
K_PK INTEGER PRIMARY KEY,
K_NAME VARCHAR,
K_DAMAGE INTEGER,
K_REWARD DOUBLE,
K_HP INTEGER,
K_SPRITE_FILE_NAME VARCHAR,
K_MATRIX_WIDTH INTEGER,
K_MATRIX_HEIGHT INTEGER
);

CREATE TABLE K_MONSTER (
K_PK INTEGER PRIMARY KEY,
K_MAP_LEVEL INTEGER,
K_WAVE INTEGER,
K_MOVE_SPEED INTEGER,
K_CHARACTER INTEGER
);

CREATE TABLE K_TOWER_CHARACTER (
K_PK INTEGER PRIMARY KEY,
K_DAMAGE INTEGER,
K_ARMOR_PIERCING INTEGER,
K_AREA_OF_EFFECT INTEGER,
K_RANGE INTEGER,
K_ATTACK_SPEED FLOAT,
K_BUY_COST INTEGER,
K_SELL_COST INTEGER,
K_SPRITE_FILE_NAME VARCHAR,
K_SPRITE_IMAGE_WIDTH INTEGER,
K_SPRITE_IMAGE_HEIGHT INTEGER,
K_SPRITE_PTILE_COLUMN INTEGER,
K_SPRITE_PTILE_ROW INTEGER,
K_MATRIX_WIDTH INTEGER,
K_MATRIX_HEIGHT INTEGER
);

INSERT INTO K_MAP VALUES ( 1, 1, 21, 14, 1 );

INSERT INTO K_PATH VALUES ( 1, 1, 0, 7, 2 );
INSERT INTO K_PATH VALUES ( 2, 1, 21, 7, -1 );

INSERT INTO K_MONSTER_CHARACTER VALUES ( 1, 'SOLDER', 3, 100, 400, 'ice-tower-I-colored.png', 1, 2);
INSERT INTO K_MONSTER VALUES ( 1, 1, 1, 15, 1 );
INSERT INTO K_MONSTER VALUES ( 1, 1, 1, 30, 1 );
INSERT INTO K_MONSTER VALUES ( 1, 1, 1, 50, 1 );


INSERT INTO K_TOWER_CHARACTER VALUES ( 1, 1, 0, 0, 3, 1, 12, 9, 'ice-tower-I-colored.png', 1500, 1485, 1, 1, 2, 2 );
INSERT INTO K_TOWER_CHARACTER VALUES ( 2, 1, 0, 0, 3, 1, 12, 9, 'basic_tower_final.png', 500, 615, 1, 1, 2, 2 );