DROP TABLE K_MAP;
DROP TABLE K_MONSTER;
DROP TABLE K_MONSTER_CHARACTER;
DROP TABLE K_PATH;
DROP TABLE K_TOWER_CHARACTER;


CREATE TABLE K_MAP (
K_PK INTEGER PRIMARY KEY,
K_LEVEL INTEGER,
K_WIDTH INTEGER,
K_HEIGHT INTEGER,
K_WAVE_NUM INTEGER
);


CREATE TABLE K_PATH (
K_PK INTEGER PRIMARY KEY,
K_MAP_LEVEL INTEGER,
K_COLUMN INTEGER,
K_ROW INTEGER,
K_NEXT_PATH INTEGER
);

CREATE TABLE K_MONSTER_CHARACTER (
K_PK INTEGER PRIMARY KEY,
K_NAME VARCHAR,
K_DAMAGE INTEGER,
K_REWARD DOUBLE
);

CREATE TABLE K_MONSTER (
K_PK INTEGER PRIMARY KEY,
K_MAP_LEVEL INTEGER,
K_WAVE INTEGER,
K_CHARACTER INTEGER
);

CREATE TABLE K_TOWER_CHARACTER (
K_PK INTEGER PRIMARY KEY,
K_DAMAGE INTEGER,
K_ARMOR_PIERCING INTEGER,
K_AREA_OF_EFFECT INTEGER,
K_RANGE INTEGER,
K_ATTACK_SPEED DOUBLE,
K_BUY_COST INTEGER,
K_SELL_COST INTEGER
);

INSERT INTO K_MAP VALUES ( 1, 1, 21, 14, 1 );

INSERT INTO K_PATH VALUES ( 1, 1, 0, 0, 2 );
INSERT INTO K_PATH VALUES ( 2, 1, 0, 14, 3 );
INSERT INTO K_PATH VALUES ( 3, 1, 21, 14, 4 );
INSERT INTO K_PATH VALUES ( 4, 1, 21, 0, 5 );
INSERT INTO K_PATH VALUES ( 5, 1, 0, 0, -1 );

INSERT INTO K_MONSTER_CHARACTER VALUES ( 1, 'SOLDER', 3, 100 );
INSERT INTO K_MONSTER VALUES ( 1, 1, 1, 1 );

INSERT INTO K_TOWER_CHARACTER VALUES ( 1, 10, 0, 0, 3, 30, 12, 9 );